name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run the build
        run: npm run gulp:build

      - name: Upload build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build
    environment: build

    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Setup nodejs
        uses: actions/setup-node@v5
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: SetPackage Version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "Version set to $VERSION"
          npm version $VERSION --no-git-tag-version 

      - name: Publish to npm
        run: npm publish --access public
